name: Build on pull request

on:
  pull_request:
  push:
    branches:
      - master

permissions:
  contents: read # check if needed
  pages: write # check if needed
  id-token: write # check if needed
  pull-requests: write
  checks: write
  statuses: write

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v3
        run: echo Checkout complete!

  build:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: Install, build, and upload your site output
        uses: withastro/action@v0
        with:
          path: .
          node-version: 18.4.1
          package-manager: npm
          run: echo Build complete!
